import { HttpStatus, Injectable } from '@nestjs/common';
import { UserAuditAction } from '@prisma/client';
import { AuditService } from '@/infrastructure/audit/audit.service';
import { PaginationQueryDto } from '@/common/dto/pagination.dto';
import {
  BusinessException,
  ConflictException,
  NotFoundException,
} from '@/common/exceptions/business.exception';
import { serialize } from '@/common/utils/bigint.util';
import { toPaginatedResult } from '@/common/utils/pagination.util';
import { resolveEntityCode } from '@/common/utils/entity-code.util';
import { BranchesRepository } from '../branches/branches.repository';
import { CreateWarehouseDto, UpdateWarehouseDto } from './dto/warehouse.dto';
import { WarehousesRepository } from './warehouses.repository';

@Injectable()
export class WarehousesService {
  constructor(
    private readonly repository: WarehousesRepository,
    private readonly branchesRepository: BranchesRepository,
    private readonly auditService: AuditService,
  ) {}

  private async validateBranch(companyId: string, branchId?: string | null, required = false) {
    if (!branchId) {
      if (required) {
        throw new BusinessException('branchId is required', HttpStatus.BAD_REQUEST, undefined, 'BRANCH_REQUIRED');
      }
      return;
    }
    const branch = await this.branchesRepository.findById(branchId, companyId);
    if (!branch) throw new NotFoundException('Branch');
  }

  async findAll(companyId: string, query: PaginationQueryDto) {
    const { items, total, page, limit } = await this.repository.findManyByCompany(companyId, query);
    return serialize(toPaginatedResult(items, total, page, limit));
  }

  async findOne(id: string, companyId: string) {
    const warehouse = await this.repository.findById(id, companyId);
    if (!warehouse) throw new NotFoundException('Warehouse');
    return serialize(warehouse);
  }

  async create(companyId: string, dto: CreateWarehouseDto, actorId: string) {
    await this.validateBranch(companyId, dto.branchId, true);

    const { code, autoGenerated } = await resolveEntityCode({
      explicitCode: dto.warehouseCode,
      name: dto.name,
      fallback: 'WH',
      isTaken: async (c) => Boolean(await this.repository.findByCode(companyId, c)),
    });

    if (!autoGenerated && (await this.repository.findByCode(companyId, code))) {
      throw new ConflictException(
        'Warehouse code already exists in this company',
        'WAREHOUSE_CODE_EXISTS',
      );
    }

    const warehouse = await this.repository.create(
      companyId,
      { ...dto, warehouseCode: code },
      actorId,
    );

    await this.auditService.log({
      companyId,
      performedBy: actorId,
      action: UserAuditAction.create,
      entityName: 'Warehouse',
      entityId: warehouse.warehouseId.toString(),
      newValue: {
        warehouseCode: code,
        name: warehouse.name,
        locationType: warehouse.locationType,
        binManagement: warehouse.binManagement,
        isDefault: warehouse.isDefault,
        autoGenerated,
      },
    });

    return serialize(warehouse);
  }

  async update(id: string, companyId: string, dto: UpdateWarehouseDto, actorId: string) {
    const existing = await this.repository.findById(id, companyId);
    if (!existing) throw new NotFoundException('Warehouse');
    await this.validateBranch(companyId, dto.branchId);

    if (dto.binManagement === false && existing.binManagement === true) {
      const activeBins = await this.repository.countActiveBins(id);
      if (activeBins > 0) {
        throw new BusinessException(
          'Cannot disable bin management while active storage bins exist',
          HttpStatus.BAD_REQUEST,
          undefined,
          'LOCATION_HAS_BINS',
        );
      }
    }

    const warehouse = await this.repository.update(id, companyId, dto, actorId);

    await this.auditService.log({
      companyId,
      performedBy: actorId,
      action: UserAuditAction.update,
      entityName: 'Warehouse',
      entityId: id,
      newValue: dto as Record<string, unknown>,
    });

    return serialize(warehouse);
  }

  async remove(id: string, companyId: string, actorId: string) {
    if (!(await this.repository.findById(id, companyId))) throw new NotFoundException('Warehouse');

    const binCount = await this.repository.countBins(id);
    if (binCount > 0) {
      throw new BusinessException(
        'Cannot delete location while storage bins exist',
        HttpStatus.BAD_REQUEST,
        undefined,
        'LOCATION_HAS_BINS',
      );
    }

    await this.repository.softDelete(id, actorId);

    await this.auditService.log({
      companyId,
      performedBy: actorId,
      action: UserAuditAction.delete,
      entityName: 'Warehouse',
      entityId: id,
    });

    return { message: 'Warehouse deleted' };
  }
}
