import { z } from 'zod';
import { createZodDto } from 'nestjs-zod';
import {
  bigintIdSchema,
  nullableBigintIdSchema,
  optionalNullableBigintIdSchema,
  optionalPatchBigintIdSchema,
} from '@/common/zod/common.schemas';

export const CreateUserSchema = z.object({
  email: z.string().email(),
  username: z.string().min(1).max(100),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  mobile: z.string().optional(),
  password: z.string().min(8),
});

export const UpdateUserSchema = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  mobile: z.string().optional(),
  timeZone: z.string().optional(),
});

const emptyToNull = (value: unknown) =>
  value === '' || value === undefined ? null : value;

/** PUT role — string digits, or null to clear the company primary role. */
export const AssignUserRoleSchema = z.object({
  roleId: nullableBigintIdSchema,
});

export const UpdateMembershipSchema = z.object({
  employeeId: z.preprocess(
    (value) => (value === '' ? null : value),
    z.string().trim().max(40).nullable().optional(),
  ),
  departmentId: optionalPatchBigintIdSchema,
  designationId: optionalPatchBigintIdSchema,
  branchId: optionalPatchBigintIdSchema,
  warehouseId: optionalPatchBigintIdSchema,
});

export const UpdateMembershipStatusSchema = z.object({
  status: z.enum(['active', 'suspended']),
});

export const ReplaceModuleAccessSchema = z.object({
  items: z
    .array(
      z.object({
        moduleId: bigintIdSchema,
        accessType: z.enum(['grant', 'deny']),
      }),
    )
    .default([]),
});

/** FE Invite User dialog — credentials generated by backend (temp password flow). */
export const InviteUserSchema = z.object({
  firstName: z.string().trim().min(1).max(100),
  lastName: z.preprocess(
    (v) => (v === null || v === undefined ? '' : v),
    z.string().trim().max(100).default(''),
  ),
  email: z.string().trim().email().max(255),
  mobile: z.preprocess(emptyToNull, z.string().trim().max(30).nullable().optional()),
  /** Login/membership employee code (UserCompany.employeeId). */
  employeeId: z.preprocess(emptyToNull, z.string().trim().max(40).nullable().optional()),
  /** Optional link to employees master row. */
  employeeRecordId: optionalNullableBigintIdSchema,
  /** EMPLOYEE links/creates employee master; EXTERNAL skips. Inferred if omitted. */
  personType: z.enum(['EMPLOYEE', 'EXTERNAL']).optional(),
  /** Accepts "34" or 34 from FE Select; null/omit = no role yet. */
  roleId: optionalNullableBigintIdSchema,
  sendInviteEmail: z.boolean().optional().default(true),
});

export class CreateUserDto extends createZodDto(CreateUserSchema) {}
export class UpdateUserDto extends createZodDto(UpdateUserSchema) {}
export class AssignUserRoleDto extends createZodDto(AssignUserRoleSchema) {}
export class InviteUserDto extends createZodDto(InviteUserSchema) {}
export class UpdateMembershipDto extends createZodDto(UpdateMembershipSchema) {}
export class UpdateMembershipStatusDto extends createZodDto(UpdateMembershipStatusSchema) {}
export class ReplaceModuleAccessDto extends createZodDto(ReplaceModuleAccessSchema) {}
