import { z } from 'zod';
import { createZodDto } from 'nestjs-zod';
import { bigintIdSchema, optionalNullableBigintIdSchema } from '@/common/zod/common.schemas';

export const CreateUserSchema = z.object({
  email: z.string().email(),
  username: z.string().min(1).max(100),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  mobile: z.string().optional(),
  password: z.string().min(8),
});

export const UpdateUserSchema = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  mobile: z.string().optional(),
  timeZone: z.string().optional(),
});

export const AssignUserRoleSchema = z.object({
  roleId: bigintIdSchema,
});

const emptyToNull = (value: unknown) =>
  value === '' || value === undefined ? null : value;

/** FE Invite User dialog — credentials generated by backend. */
export const InviteUserSchema = z.object({
  firstName: z.string().trim().min(1).max(100),
  lastName: z.preprocess(
    (v) => (v === null || v === undefined ? '' : v),
    z.string().trim().max(100).default(''),
  ),
  email: z.string().trim().email().max(255),
  mobile: z.preprocess(emptyToNull, z.string().trim().max(30).nullable().optional()),
  employeeId: z.preprocess(emptyToNull, z.string().trim().max(40).nullable().optional()),
  /** Accepts "34" or 34 from FE Select; null/omit = no role yet. */
  roleId: optionalNullableBigintIdSchema,
  sendInviteEmail: z.boolean().optional().default(true),
});

export class CreateUserDto extends createZodDto(CreateUserSchema) {}
export class UpdateUserDto extends createZodDto(UpdateUserSchema) {}
export class AssignUserRoleDto extends createZodDto(AssignUserRoleSchema) {}
export class InviteUserDto extends createZodDto(InviteUserSchema) {}
