-- Security & Organization V1
-- Adds permission sets, effective permission links, and data access policies.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'data_scope_type') THEN
    CREATE TYPE "data_scope_type" AS ENUM ('branch', 'department', 'warehouse');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS "permission_sets" (
  "permission_set_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" BIGINT NOT NULL,
  "code" VARCHAR(60) NOT NULL,
  "name" VARCHAR(120) NOT NULL,
  "description" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_by" BIGINT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_by" BIGINT,
  "updated_at" TIMESTAMP(3),
  "deleted_by" BIGINT,
  "deleted_at" TIMESTAMP(3),
  "row_version" INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT "permission_sets_company_id_fkey"
    FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "permission_sets_company_id_code_key"
  ON "permission_sets" ("company_id", "code");
CREATE INDEX IF NOT EXISTS "permission_sets_company_id_idx"
  ON "permission_sets" ("company_id");

CREATE TABLE IF NOT EXISTS "permission_set_permissions" (
  "permission_set_permission_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "permission_set_id" BIGINT NOT NULL,
  "permission_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "permission_set_permissions_permission_set_id_fkey"
    FOREIGN KEY ("permission_set_id") REFERENCES "permission_sets"("permission_set_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "permission_set_permissions_permission_id_fkey"
    FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "permission_set_permissions_permission_set_id_permission_id_key"
  ON "permission_set_permissions" ("permission_set_id", "permission_id");
CREATE INDEX IF NOT EXISTS "permission_set_permissions_permission_set_id_idx"
  ON "permission_set_permissions" ("permission_set_id");

CREATE TABLE IF NOT EXISTS "role_permission_sets" (
  "role_permission_set_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" BIGINT NOT NULL,
  "permission_set_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "role_permission_sets_role_id_fkey"
    FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "role_permission_sets_permission_set_id_fkey"
    FOREIGN KEY ("permission_set_id") REFERENCES "permission_sets"("permission_set_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "role_permission_sets_role_id_permission_set_id_key"
  ON "role_permission_sets" ("role_id", "permission_set_id");
CREATE INDEX IF NOT EXISTS "role_permission_sets_role_id_idx"
  ON "role_permission_sets" ("role_id");

CREATE TABLE IF NOT EXISTS "data_access_policies" (
  "policy_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" BIGINT NOT NULL,
  "code" VARCHAR(60),
  "name" VARCHAR(120) NOT NULL,
  "description" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_by" BIGINT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_by" BIGINT,
  "updated_at" TIMESTAMP(3),
  "deleted_by" BIGINT,
  "deleted_at" TIMESTAMP(3),
  "row_version" INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT "data_access_policies_company_id_fkey"
    FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "data_access_policies_company_id_code_key"
  ON "data_access_policies" ("company_id", "code");
CREATE INDEX IF NOT EXISTS "data_access_policies_company_id_idx"
  ON "data_access_policies" ("company_id");

CREATE TABLE IF NOT EXISTS "data_access_policy_scopes" (
  "policy_scope_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "policy_id" BIGINT NOT NULL,
  "scope_type" "data_scope_type" NOT NULL,
  "scope_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "data_access_policy_scopes_policy_id_fkey"
    FOREIGN KEY ("policy_id") REFERENCES "data_access_policies"("policy_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "data_access_policy_scopes_policy_id_scope_type_scope_id_key"
  ON "data_access_policy_scopes" ("policy_id", "scope_type", "scope_id");
CREATE INDEX IF NOT EXISTS "data_access_policy_scopes_policy_id_scope_type_idx"
  ON "data_access_policy_scopes" ("policy_id", "scope_type");

CREATE TABLE IF NOT EXISTS "user_data_access_policies" (
  "user_data_access_policy_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  "policy_id" BIGINT NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "user_data_access_policies_company_id_fkey"
    FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "user_data_access_policies_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "user_data_access_policies_policy_id_fkey"
    FOREIGN KEY ("policy_id") REFERENCES "data_access_policies"("policy_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "user_data_access_policies_company_id_user_id_policy_id_key"
  ON "user_data_access_policies" ("company_id", "user_id", "policy_id");
CREATE INDEX IF NOT EXISTS "user_data_access_policies_company_id_user_id_idx"
  ON "user_data_access_policies" ("company_id", "user_id");
