export const ENTITLEMENT_ERROR_CODES = {
  MODULE_NOT_ENTITLED: 'MODULE_NOT_ENTITLED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  MODULE_DISABLED: 'MODULE_DISABLED',
} as const;

export type EntitlementErrorCode =
  (typeof ENTITLEMENT_ERROR_CODES)[keyof typeof ENTITLEMENT_ERROR_CODES];
