-- Employees master (HR/org person). Separate from users (login identity).
-- user_id is nullable so an Employee can exist before invitation.

CREATE TYPE "employment_status" AS ENUM ('active', 'inactive', 'terminated', 'on_leave');
CREATE TYPE "employment_type" AS ENUM ('full_time', 'part_time', 'contract', 'intern', 'consultant');

CREATE TABLE IF NOT EXISTS "employees" (
  "employee_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" BIGINT NOT NULL,
  "user_id" BIGINT,
  "employee_code" VARCHAR(40) NOT NULL,
  "first_name" VARCHAR(100) NOT NULL,
  "last_name" VARCHAR(100),
  "email" VARCHAR(255),
  "mobile" VARCHAR(30),
  "branch_id" BIGINT,
  "department_id" BIGINT,
  "designation_id" BIGINT,
  "reporting_manager_id" BIGINT,
  "joining_date" DATE,
  "employment_type" "employment_type",
  "employment_status" "employment_status" NOT NULL DEFAULT 'active',
  "profile_photo" VARCHAR(500),
  "profile_completion_percentage" SMALLINT NOT NULL DEFAULT 0,
  "created_by" BIGINT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_by" BIGINT,
  "updated_at" TIMESTAMP(3),
  "deleted_by" BIGINT,
  "deleted_at" TIMESTAMP(3),
  "row_version" INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT "employees_company_id_fkey"
    FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "employees_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "employees_branch_id_fkey"
    FOREIGN KEY ("branch_id") REFERENCES "branches"("branch_id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "employees_department_id_fkey"
    FOREIGN KEY ("department_id") REFERENCES "departments"("department_id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "employees_designation_id_fkey"
    FOREIGN KEY ("designation_id") REFERENCES "designations"("designation_id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "employees_reporting_manager_id_fkey"
    FOREIGN KEY ("reporting_manager_id") REFERENCES "employees"("employee_id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "employees_company_id_employee_code_key"
  ON "employees" ("company_id", "employee_code");

CREATE INDEX IF NOT EXISTS "employees_company_id_idx"
  ON "employees" ("company_id");

CREATE INDEX IF NOT EXISTS "employees_user_id_idx"
  ON "employees" ("user_id");

CREATE INDEX IF NOT EXISTS "employees_company_id_employment_status_idx"
  ON "employees" ("company_id", "employment_status");
