-- Item Master: company-scoped AUTO/MANUAL item code mode (default AUTO)

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'item_code_mode') THEN
    CREATE TYPE "item_code_mode" AS ENUM ('AUTO', 'MANUAL');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS "company_item_settings" (
  "settings_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" BIGINT NOT NULL,
  "item_code_mode" "item_code_mode" NOT NULL DEFAULT 'AUTO',
  "item_code_prefix" VARCHAR(10) NOT NULL DEFAULT 'ITM',
  "created_by" BIGINT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_by" BIGINT,
  "updated_at" TIMESTAMP(3),
  CONSTRAINT "company_item_settings_company_id_fkey"
    FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "company_item_settings_company_id_key"
  ON "company_item_settings" ("company_id");
