-- Data Access Policy V1 normalize
-- Split generic scopes into branch / department / warehouse junction tables.
-- Empty policy scope = no data access (enforced in application layer).

-- 1) Ensure policy codes are non-null before NOT NULL constraint
UPDATE "data_access_policies"
SET "code" = 'POLICY_' || "policy_id"::text
WHERE "code" IS NULL OR btrim("code") = '';

ALTER TABLE "data_access_policies"
  ALTER COLUMN "code" SET NOT NULL;

-- 2) Junction tables
CREATE TABLE IF NOT EXISTS "data_access_policy_branches" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "policy_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "data_access_policy_branches_policy_id_fkey"
    FOREIGN KEY ("policy_id") REFERENCES "data_access_policies"("policy_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "data_access_policy_branches_branch_id_fkey"
    FOREIGN KEY ("branch_id") REFERENCES "branches"("branch_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "data_access_policy_branches_policy_id_branch_id_key"
  ON "data_access_policy_branches" ("policy_id", "branch_id");
CREATE INDEX IF NOT EXISTS "data_access_policy_branches_policy_id_idx"
  ON "data_access_policy_branches" ("policy_id");
CREATE INDEX IF NOT EXISTS "data_access_policy_branches_branch_id_idx"
  ON "data_access_policy_branches" ("branch_id");

CREATE TABLE IF NOT EXISTS "data_access_policy_departments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "policy_id" BIGINT NOT NULL,
  "department_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "data_access_policy_departments_policy_id_fkey"
    FOREIGN KEY ("policy_id") REFERENCES "data_access_policies"("policy_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "data_access_policy_departments_department_id_fkey"
    FOREIGN KEY ("department_id") REFERENCES "departments"("department_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "data_access_policy_departments_policy_id_department_id_key"
  ON "data_access_policy_departments" ("policy_id", "department_id");
CREATE INDEX IF NOT EXISTS "data_access_policy_departments_policy_id_idx"
  ON "data_access_policy_departments" ("policy_id");
CREATE INDEX IF NOT EXISTS "data_access_policy_departments_department_id_idx"
  ON "data_access_policy_departments" ("department_id");

CREATE TABLE IF NOT EXISTS "data_access_policy_warehouses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "policy_id" BIGINT NOT NULL,
  "warehouse_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "data_access_policy_warehouses_policy_id_fkey"
    FOREIGN KEY ("policy_id") REFERENCES "data_access_policies"("policy_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "data_access_policy_warehouses_warehouse_id_fkey"
    FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("warehouse_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "data_access_policy_warehouses_policy_id_warehouse_id_key"
  ON "data_access_policy_warehouses" ("policy_id", "warehouse_id");
CREATE INDEX IF NOT EXISTS "data_access_policy_warehouses_policy_id_idx"
  ON "data_access_policy_warehouses" ("policy_id");
CREATE INDEX IF NOT EXISTS "data_access_policy_warehouses_warehouse_id_idx"
  ON "data_access_policy_warehouses" ("warehouse_id");

-- 3) Migrate legacy polymorphic scopes (if table still exists)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'data_access_policy_scopes'
  ) THEN
    INSERT INTO "data_access_policy_branches" ("policy_id", "branch_id", "created_at")
    SELECT s."policy_id", s."scope_id", s."created_at"
    FROM "data_access_policy_scopes" s
    INNER JOIN "branches" b ON b."branch_id" = s."scope_id"
    WHERE s."scope_type" = 'branch'
    ON CONFLICT ("policy_id", "branch_id") DO NOTHING;

    INSERT INTO "data_access_policy_departments" ("policy_id", "department_id", "created_at")
    SELECT s."policy_id", s."scope_id", s."created_at"
    FROM "data_access_policy_scopes" s
    INNER JOIN "departments" d ON d."department_id" = s."scope_id"
    WHERE s."scope_type" = 'department'
    ON CONFLICT ("policy_id", "department_id") DO NOTHING;

    INSERT INTO "data_access_policy_warehouses" ("policy_id", "warehouse_id", "created_at")
    SELECT s."policy_id", s."scope_id", s."created_at"
    FROM "data_access_policy_scopes" s
    INNER JOIN "warehouses" w ON w."warehouse_id" = s."scope_id"
    WHERE s."scope_type" = 'warehouse'
    ON CONFLICT ("policy_id", "warehouse_id") DO NOTHING;

    DROP TABLE "data_access_policy_scopes";
  END IF;
END
$$;

-- 4) Drop unused enum if no longer referenced
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'data_scope_type') THEN
    DROP TYPE "data_scope_type";
  END IF;
END
$$;

-- 5) user assignment updated_at
ALTER TABLE "user_data_access_policies"
  ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3);
