import { normalizeEntityCodeBase, resolveEntityCode } from './entity-code.util';

describe('normalizeEntityCodeBase', () => {
  it('normalizes name to UPPER_SNAKE', () => {
    expect(normalizeEntityCodeBase('Head Office', 'BR')).toBe('HEAD_OFFICE');
  });

  it('collapses punctuation and underscores', () => {
    expect(normalizeEntityCodeBase('WH-HQ!!', 'WH')).toBe('WH_HQ');
  });

  it('uses fallback when empty', () => {
    expect(normalizeEntityCodeBase('   ', 'DEPT')).toBe('DEPT');
    expect(normalizeEntityCodeBase('@@@', 'DESIG')).toBe('DESIG');
  });
});

describe('resolveEntityCode', () => {
  it('auto-generates from name and suffixes when taken', async () => {
    const taken = new Set(['HEAD_OFFICE']);
    const result = await resolveEntityCode({
      name: 'Head Office',
      fallback: 'BR',
      isTaken: async (c) => taken.has(c),
    });
    expect(result).toEqual({ code: 'HEAD_OFFICE_2', autoGenerated: true });
  });

  it('returns explicit code without suffixing', async () => {
    const result = await resolveEntityCode({
      explicitCode: 'hq',
      name: 'Head Office',
      fallback: 'BR',
      isTaken: async () => true,
    });
    expect(result).toEqual({ code: 'HQ', autoGenerated: false });
  });

  it('treats blank explicit as auto', async () => {
    const result = await resolveEntityCode({
      explicitCode: '  ',
      name: 'Main Store',
      fallback: 'WH',
      isTaken: async () => false,
    });
    expect(result).toEqual({ code: 'MAIN_STORE', autoGenerated: true });
  });
});
