/** Shared org/entity code generation (branch, department, designation, warehouse, …). */

export const ORG_CODE_MAX_LENGTH = 30;

/**
 * Normalize a human label or client-supplied code into UPPER_SNAKE.
 * Empty / unusable input → fallback (e.g. BR, DEPT, WH).
 */
export function normalizeEntityCodeBase(raw: string, fallback: string): string {
  const normalized = String(raw ?? '')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');

  if (!normalized) return fallback.slice(0, ORG_CODE_MAX_LENGTH);
  return normalized.slice(0, ORG_CODE_MAX_LENGTH);
}

/**
 * Prefer explicit code when provided; otherwise derive from name.
 * Explicit codes that collide → ConflictException at call site (no auto-suffix).
 * Auto codes get _2, _3… until unique.
 */
export async function resolveEntityCode(params: {
  explicitCode?: string | null;
  name: string;
  fallback: string;
  isTaken: (code: string) => Promise<boolean>;
}): Promise<{ code: string; autoGenerated: boolean }> {
  if (params.explicitCode != null && String(params.explicitCode).trim() !== '') {
    const code = normalizeEntityCodeBase(String(params.explicitCode), params.fallback);
    return { code, autoGenerated: false };
  }

  const base = normalizeEntityCodeBase(params.name, params.fallback);
  let candidate = base;
  let n = 1;

  while (await params.isTaken(candidate)) {
    n += 1;
    const suffix = `_${n}`;
    const maxBase = ORG_CODE_MAX_LENGTH - suffix.length;
    candidate = `${base.slice(0, Math.max(1, maxBase))}${suffix}`;
  }

  return { code: candidate, autoGenerated: true };
}
